name: qr_flutter_wc
description: A WalletConnect's small modification of QR.FLUTTER repository https://github.com/theyakka/qr.flutter to have the QR Code shown as needed per our requirements
version: 0.0.3
homepage: https://github.com/WalletConnect/qr.flutter

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  qr: ^3.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
